//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public byte idProducto { get; set; }
        public string nombre { get; set; }
        public byte idProveedor { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
